### ISSUE TITLE
Create container hierarchy 

### ISSUE THREAD

**Issue by richarda23** [richarda23/rspace-cli#6]
This is to support easy creation of container trees for new inventory module, branch inv-29
Container tree can be specified in yaml, e.g.

``` yaml
name: Bob's Lab freezer
containers:
- name: draw 1
  containers:
  - name: lab antibodies
    rows: 6
    columns: 8
  - name: Bob's antibodies
    rows: 6
    columns: 8
  - name: PCR stuff
  - name: Miscellaneous
- name: draw 2
  containers: 
  - name: top rack
  - name: bottom rack
- name: draw 3
  containers:
  - name: PCR kit
  - name: Topo2 kit
  - name: RNAi (fly) kit

```
